# Application Name
spring.application.name=Project

# Database Configuration (MySQL)
spring.datasource.url=jdbc:mysql://localhost:3306/co2123db
spring.datasource.username=root
spring.datasource.password=Password123
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Hibernate (JPA) Properties
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect

# Thymeleaf Configuration
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.enabled=true

# Server Port
server.port=8080

# Spring Security Default User
spring.security.user.name=admin
spring.security.user.password=admin123

# Logging Level
logging.level.org.springframework=INFO
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

# Static Resources

spring.web.resources.static-locations=classpath:/static/
