spring.application.name=gradetracker

# H2 Database Configuration (In-Memory)
spring.datasource.url=jdbc:h2:mem:gradetracker
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.h2.console.enabled=true
